map_radius: 30
hex_size:
- 10.0
- 10.0
seed: null
zoom_speed: 1.0
starting_budget: 50
tower_config:
  tower_type:
    Small:
      cost: 8
      scale: 0.8
    Medium:
      cost: 20
      scale: 1.0
    Large:
      cost: 50
      scale: 1.5
  damaging_rate: 0.5
  tower_damage_alpha: 0.7
enemy_config:
  enemy_spawn_rate: 0.01
  base_speed: 1.0
  min_max_health:
  - 5
  - 20
game_length: 300.0
game_over_timer_length: 5.0
